#!/usr/bin/env zsh

# creates a modman file with directories (risky) nor documentation
: ${(A)=module:=$(ls -1rtdp htdocs/**/*([^txt|^pdf])(^/))} &&\
print -l ${(@)module[@]} | sed -rn 's|htdocs/(.*)$|htdocs/\1 \1|p' > modman


